#!/usr/bin/env php
<?php
$serverName = 'localhost';
if (!empty($argv)) {
    foreach($argv as $index => $arg) {
        if ($arg == '-p' or $arg == '--production') {
            $serverName = 'production';
            unset($argv[$index]);
        }
        elseif ($arg == '-t' or $arg == '--test') {
            $serverName = 'test';
            unset($argv[$index]);
        }
    }
}
require_once('bootstrap.php');
$app = __setupApp($serverName);

use Skully\Console\Console;
$consoleApp = new Console($app);
array_shift($argv);
try {
    $consoleApp->run(implode(' ', $argv));
}
catch (Exception $e) {
    echo $e->getMessage();
}
